//
// Generated file, do not edit! Created by opp_msgc 4.1 from linklayer/internal/Delivery.msg.
//

#ifndef _DELIVERY_M_H_
#define _DELIVERY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>linklayer/internal/Delivery.msg</tt> by opp_msgc.
 * <pre>
 * packet Delivery extends cPacket
 * {
 * 	int ArrivalPort;
 * 	int SendByPort;
 * 
 * }
 * </pre>
 */
class Delivery : public ::cPacket
{
  protected:
    int ArrivalPort_var;
    int SendByPort_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Delivery&);

  public:
    Delivery(const char *name=NULL, int kind=0);
    Delivery(const Delivery& other);
    virtual ~Delivery();
    Delivery& operator=(const Delivery& other);
    virtual Delivery *dup() const {return new Delivery(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getArrivalPort() const;
    virtual void setArrivalPort(int ArrivalPort_var);
    virtual int getSendByPort() const;
    virtual void setSendByPort(int SendByPort_var);
};

inline void doPacking(cCommBuffer *b, Delivery& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Delivery& obj) {obj.parsimUnpack(b);}


#endif // _DELIVERY_M_H_
